version: '3.8'

services:
  buildmate-frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped